### ISSUE TITLE
Model changes for Letter

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#10]
- Change representation in Django Admin. Instead of "letter #57" there should be a name / one-line identifier so the team can quickly find/identify new letters, e.g. ('No. 60: Boniface to pope Zacharias in 578')
- Add `sender`
- Add `addressee`
- Add `date`
- Add `type` (e.g. 'friendship letter', 'consensus letter', 'royal order'). This could be an editable category in its own right?
- Instead of `certainty`, two new fields: `historically_attested` (letter features in actual, historical events vs. letter features in story/legend/fairytale) and `mentioned`: (letter is directly mentioned vs. existence of letter is implied/possible).

**Comment by lukavdplas** [comment]
I would think that the `sender`, `addressee` and `date` fields can be inferred from the actions/roles associated with the letter?
