### ISSUE TITLE
Groups of People

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#12]
We should have a model for `Groups of people`. I guess users should also be allowed to indicate that individual `Person`s are part of a group.

**Comment by XanderVertegaal** [comment]
Related to this: the `Role` model now accepts only one `Person`. It makes sense to make it accept multiple instances of `Person` and `PersonGroup` (or whatever we decide to call the groups of people.

**Comment by lukavdplas** [comment]
It makes sense that `Role` only accepts one person - if multiple people are involved in an action, they each have their own `Role` (though the nature of the role can be the same for multiple actors).

**Comment by XanderVertegaal** [comment]
We are going to keep the same Person model for this, but rename it to Agent. The model needs an additional field `is_group`. We can then also add another value for Gender (`mixed`), which should only be selected if `is_group` is set to `True`. Fields such as `PersonDateOfBirth` and `PersonDateOfDeath` are not relevant for groups.
