### ISSUE TITLE
Sort episodes by book/chapter/page

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#122]
The order of episodes is now based on ID (by default), which is not always logical.

**Comment by lukavdplas** [comment]
In the last meeting with the researchers, I discussed how episodes should be sorted. (One issue is that book/chapter/page are currently string fields.)

It looks like it should be okay to turn page (or page range) into an integer field and sort on that; this should be defined for all the data. However, you can have multiple episodes on the same page, so *ideally* there would also be a way to indicate the relative order within a page.
