### ISSUE TITLE
Social status on `Person` model

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#19]
I am not sure how to implement the requested 'Social status' field on the `Person` model. We could use relative markers such as 'high'/'middle'/'low', but that feels too modern and not very insightful.

Presumably, social _classes_ such as 'nobility', 'clergy', 'peasantry' are meant, but we should ask whether a fixed list will suffice or whether this is something they want to have control over.

**Comment by lukavdplas** [comment]
I was wondering about this too. I expect we'll end up with a few categories like you suggest, that won't be changed on the fly, so it will be easier to hard-code them.

**Comment by XanderVertegaal** [comment]
Occupation is to be renamed to Status and should indicate more than just a person's job.
