### ISSUE TITLE
Mock-up for data entry form

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#31]
Data entry flow -- how would a research assistant enter new data into the database, starting from the sources.

1. Source overview => user selects/adds source
2. Entity overview (Agents / Objects / Places) => user selects/adds entity
3. Entity detail form => user enters details of agent/object/place as they occur in the source.
4. Uniquely identifiable: is the entity generic (e.g. 'a shepherd', 'a forest', 'a cask of beer') or unique identifiable ('St. Radegund', 'the monastery of Toulouse', 'the sceptre of Charlemagne')?
5. Link to existing records. (Should the research assistant do this, or will core team members do this?)

See photo below.

![image](https://github.com/CentreForDigitalHumanities/lettercraft/assets/73882506/d46c215e-0867-44d9-bc51-4edf45bdf5e9)

**Comment by lukavdplas** [comment]
Current status:

#35 implements a menu to edit the data for a source, and a form to edit a depiction of an agent in a source.

I'm currently working on adding some more detail for objects and spaces. We'll try to work out actions as well in the future.
