### ISSUE TITLE
Causation

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#51]
How do we link events to one another? How do we express causation? Is a field `associated_events` enough, or do we explicitly want to mark how events are related?

**Comment by jgonggrijp** [comment]
Perhaps you could use/borrow from the Activity Streams standard vocabulary. In particular, `as:result` might roughly express the type of relation you are looking for.

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-result
