### ISSUE TITLE
Authentication-based routing

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#68]
This becomes relevant once we have more non-authentication routes.

- The user should be brought back to the page they were on when going through the logging flow.
- Route guards provide better UX.

**Comment by lukavdplas** [comment]
I-analyzer has a [LoggedOnGuard](https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/develop/frontend/src/app/logged-on.guard.ts) which I forgot to transfer; that should be a good basis.
