### ISSUE TITLE
Implement GraphQL

### ISSUE THREAD

**Issue by lukavdplas** [CentreForDigitalHumanities/lettercraft#75]

**Comment by XanderVertegaal** [comment]
- [x] Create endpoint, set up Apollo + Graphene
 - [x] Implement types + queries for Source app
 - [x] Implement types + queries for Person app
 - [ ] Implement types + queries for Event app
 - [ ] Implement types + queries for Letter app
 - [ ] Implement types + queries for Space app
 - [ ] Implement types + queries for Person app
 - [ ] Implement types + queries for Event app
 - [ ] Implement types + queries for Letter app
 - [ ] Implement types + queries for Space app
