### ISSUE TITLE
Handle CSRF on GraphQL endpoint

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/lettercraft#82]
Currently, `/api/graphql` is exempt from CSRF.

![image](https://github.com/CentreForDigitalHumanities/lettercraft/assets/73882506/c8983089-f0c1-4cfe-be0d-6bbf7706e872)

We could solve this by sending CSRF-tokens along with every request, or by implementing a good user/permission system, which ensures that non-authenticated users are not able to query/mutate anything.

**Comment by lukavdplas** [comment]
Our conclusion for now: since this is an API, arguably cross-site requests are a feature, not a bug. Since we have middleware to ensure users must be authenticated to make mutations, it seems fine that this endpoint is CSRF-exempt.

**Comment by jgonggrijp** [comment]
If your API supports session authentication, you still need CSRF protection.

CSRF protection is not meant to prevent cross-origin requests. Rather, it is meant to prevent malicious sites from presenting a form to genuine users of your application and tricking them into submitting it to your endpoint with their established session cookie.
